biblioteca/urls.py
from django.contrib import admin
from django.urls import path,include
from homepage import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/', include('blog.urls'))
]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path,include
from . import views

app_name='blog'

urlpatterns = [
    path('',views.all_blogs, name='all_blogs'),
    path('<int:nr_id>/',views.blog_id,name='blog_id')
    ]

blog/models.py
from django.db import models

class Blog(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    date = models.DateField()
    image = models.ImageField(upload_to='blog/images')


    def __str__(self):
        return self.title

homepage/models.py
from django.db import models

blog/views.py
from django.shortcuts import render,get_object_or_404
from .models import Blog

def all_blogs(request):
    blog = Blog.objects.order_by('-date')
    return render(request,'blog/all_blogs.html',{'blog':blog})

def blog_id(request,nr_id):
    post = get_object_or_404(Blog,pk=nr_id)
    return render(request,'blog/blog_id.html',{'post':post})

homepage/views.py
from django.shortcuts import render

def home(request):
    return render(request,'homepage/home.html')

blog/templates/blog/all_blogs.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blogs</title>
    <style>
    * {
        margin: 0px;
        padding: 0px;
        box-sizing: border-box;
      }
      html {
        font-size: 62.5%;
        }

      .navbar {
        margin: 0.2rem 0.3rem 0.2rem 103rem;
      }

      .navbar button {
        padding: 1rem 2rem;
        background-color: rgb(220, 217, 224);
        border: 0.1rem solid rgb(124, 119, 192);
        margin: 0.6rem 0.2rem;
        border-radius: 0.5rem;
        border-top-left-radius: 1rem;
        border-bottom-right-radius: 1rem;
      }
      h1 {
        color: rgb(199, 153, 37);
        margin: 0.1rem 10rem 0.2rem 15rem;
        padding: 0.1rem 2rem 2rem 2rem;
        position: center;
        font-size: 3rem;
        text-align: center;
      }
      h3 {
          color: rgb(9, 9, 75);
          font-size: 2rem;
          text-align: center;
      }

      h2 {
          color: rgb(114, 55, 55);
          font-size: 2rem;
          text-align: center;
          margin: 1rem ;
      }
      h4 {
          color: rgb(114, 55, 55);
          font-size: 2rem;
          text-align: center;
          margin: 1rem ;
      }
      img {
        margin: 1rem 55rem;
      }
      html {
      background-color : rgb(185, 194, 155);
      }

    </style>
</head>
<body>
    <nav class="navbar">
      <button><a href="{% url 'home' %}">Home</a></button>
      <button><a href="{% url 'blog:all_blogs' %}">Blog</a></button>
      <button><a href="https://www.youtube.com/watch?v=kMTVWAWC7Qc">Copii</a></button>
      <button><a href="https://bragadancatalin.wixsite.com/website/about">About</a></button>
    </nav>
    <h1>Aceasta este pagina blogului</h1>
    {% for x in blog %}
    <a href="{% url 'blog:blog_id' x.id %}"><h2><h2>{{x.title}}</h2><img src="{{x.image.url}}" height="200" width="300"></h2></a>
    <h3>Scurta descriere: {{x.description |striptags| truncatechars:50 }}</h3>
    <h4>{{x.date}}</h4>
    {% endfor %}



</body>
</html>

blog/templates/blog/blog_id.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>blog posts</title>
    <style>
        h1 {
        color: rgb(9, 32, 75);
        margin: 0.1rem 10rem 0.2rem 15rem;
        padding: 0.1rem 2rem 2rem 2rem;
        position: center;
        font-size: 3rem;
        text-align: center;
      }
      * {
        margin: 0px;
        padding: 0px;
        box-sizing: border-box;
      }
      html {
        font-size: 62.5%;
        background-color : rgb(185, 194, 155);
        }

      .navbar {
        margin: 0.2rem 0.3rem 0.2rem 103rem;
      }

      .navbar button {
        padding: 1rem 2rem;
        background-color: rgb(220, 217, 224);
        border: 0.1rem solid rgb(124, 119, 192);
        margin: 0.6rem 0.3rem;
        border-radius: 0.5rem;
        border-top-left-radius: 1rem;
        border-bottom-right-radius: 1rem;
      }
       img {
          width: 30%;
          height: 35rem;
          padding: 3rem 1rem;
          margin: 2rem 50rem;

        }
        h2 {
        color: rgb(104, 65, 104);
        margin: 0.1rem 10rem 0.2rem 15rem;
        padding: 0.1rem 2rem 2rem 2rem;
        position: center;
        font-size: 2rem;
        text-align: center;
        }
        h3 {
        color: rgb(104, 65, 104);
        margin: 2rem 10rem 0.2rem 15rem;
        padding: 0.1rem 2rem 2rem 2rem;
        position: center;
        font-size: 3rem;
        text-align: center;
        }

    </style>
</head>
    <body>
     <nav class="navbar">
      <button><a href="{% url 'home' %}">Home</a></button>
      <button><a href="{% url 'blog:all_blogs' %}">Blog</a></button>
      <button><a href="https://www.youtube.com/watch?v=kMTVWAWC7Qc">Copii</a></button>
      <button><a href="https://bragadancatalin.wixsite.com/website/about">About</a></button>
    </nav>
    <h1>{{post.title}}</h1>
    <img src ="{{post.image.url}}" height=100 width=200>

    <h2>{{post.date}}</h2>
    <h3>{{post.description|safe}}</h3>
    </body>
</html>

homepage/templates/homepage/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta
      name="description"
      content="O pagina distractiva a Bibliotecii Judetene Mehedinti!"
    />
    <link rel="icon" href="media/homepage/image/books_library_1768.ico"/>

    <title>Bjm</title>
    <style>

        * {
        margin: 0px;
        padding: 0px;
        box-sizing: border-box;
      }
      html {
        font-size: 62.5%;
      }
      h1 {
        color: rgb(199, 153, 37);
        margin: 0.1rem 10rem 0.2rem 15rem;
        padding: 0.1rem 2rem 2rem 2rem;
        position: center;
        font-size: 3rem;
        text-align: center;
      }

      img {
        height: 48rem;
        width: 100%;
      }

      .navbar {
        margin: 0.2rem 0.3rem 0.2rem 103rem;
      }

      .navbar button {
        padding: 1rem 2rem;
        background-color: rgb(220, 217, 224);
        border: 0.1rem solid rgb(124, 119, 192);
        margin: 0.6rem 0.3rem;
        border-radius: 0.5rem;
        border-top-left-radius: 1rem;
        border-bottom-right-radius: 1rem;
      }

      .home a {
        color: rgb(124, 119, 192);
        font-size: 1.5rem;
      }

      .poze img {
        width: 30%;
        height: 35rem;
        padding: 3rem 1rem;
        margin: 2rem 1rem 2rem 1rem;
      }

      .sf h2 {
        color: rgb(199, 153, 37);
        margin: auto;
        padding: 0.1rem 2rem 2rem 2rem;
        position: center;
        font-size: 3rem;
        text-align: center;
      }
    </style>
  </head>
  <body>
    <nav class="navbar">
      <button><a href="{% url 'home' %}">Home</a></button>
      <button><a href="{% url 'blog:all_blogs' %}">Blog</a></button>
      <button><a href="https://www.youtube.com/watch?v=kMTVWAWC7Qc">Copii</a></button>
      <button><a href="https://bragadancatalin.wixsite.com/website/about">About</a></button>
    </nav>
    <h1 class="first-title">
      Bine ati venit!Ne-am gandit sa va oferim un preview pentru crash course-ul
      de HTML si CSS pentru viitor la biblioteca!!!
    </h1>
    {% load static %}
    <img src="media/homepage/image/white-book-in-white-table-near-yellow-wall-3760323.jpg"/>
    <br /><video
      controls
      src="media/homepage/image/y2mate.com - code_stars_short_film_dU1xS07N-FA_1080p.mp4"
      width="100%"
      height="700"
    ></video>
    <figure class="poze">
      <img src="media/homepage/image/book-chapter-six-5834.jpg"/>
      <img src="media/homepage/image/Screenshot_2.png" />
      <img src="media/homepage/image/photo-of-teacup-on-top-of-books-1831744.jpg" />
    </figure>
    <footer class="sf">
      <h2>
        Si tu poti crea un webpage ca acesta! Te asteptam cu drag la biblioteca!
      </h2>
    </footer>
  </body>
</html>